version: "3.1"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: anastasia
      POSTGRES_DB: vk
      POSTGRES_PASSWORD: 2553
    ports:
      - "5432:5432"
